### ISSUE TITLE
maximum-of (or minimum-of ;) ) has a wrong name

### ISSUE THREAD

**Issue by luce80** [greggirwin/red-hof#2]
maximum-of (or minimum-of ;) ) has a wrong name

**Comment by hiiamboris** [comment]
what's the *right* name?

**Comment by greggirwin** [comment]
I have many thoughts on the R2 design, but Red doesn't have them at all yet.

**Comment by luce80** [comment]
Ehm, they shouldn't both be called `minimum-of` :) . Sorry for not using the word `typo` .

**Comment by greggirwin** [comment]
Indeed. In %mapfold.red the second one uses `max` internally, and is misnamed.

**Comment by hiiamboris** [comment]
Fixed, thanks
